### ISSUE TITLE
Xdefi extension update for terra 2.0 

### ISSUE THREAD

**Issue by ap-justin** [XDeFi-tech/examples-dapps-sdk#14]
Hi, would there be an update for terra v2.0 ?

**Comment by davidp94** [comment]
> Hi, would there be an update for terra v2.0 ?

Yes we will update the docs once we ship Terra V2 support

**Comment by dimitrykislichenko** [comment]
@ap-justin you won't need any changes required from your side, users will be able to pick chain them self, though you may want to add validation of selected chain to report to the user if chain is incorrect.

<img width="376" alt="Screenshot 2022-06-05 at 13 05 38" src="https://user-images.githubusercontent.com/1087878/172046073-96b76509-6de5-4ca0-a543-0ba34d47c7c0.png">
